### ISSUE TITLE
📝 Documentation: Explain what a "platform" is in the README.md

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/emoji-platform-data#13]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/emoji-platform-data/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Mentioned by `@vladimyr.bsky.social`: https://bsky.app/profile/vladimyr.bsky.social/post/3kobgczibuu2b.

> Minor suggestion: the platform is kind of an ambiguous term (Is it an app, an OS?) so it might be useful to put an exact definition somewhere inside README 💡

Agreed. Thanks for suggesting! _(are you on GitHub? let me know, I'd love to give you an all-contributors recognition here)_

### Additional Info

I'll take this so I can explain myself. 😅 

Co-authored-by: @vladimyr

**Comment by vladimyr** [comment]
> Agreed. Thanks for suggesting! _(are you on GitHub? let me know, I'd love to give you an all-contributors recognition here)_

Hi from the GitHub end 👋 and thanks for the recognition!
